#!/bin/bash
# -

echo -n "BACKUPS :: STARTING" | logger

# SETUP
mkdir -p ~/.backups/backups
cd ~/.backups/backups

###############################################################################

# APACHE
echo -n "BACKUPS :: ... Apache Config Files / Host File" | logger

mkdir -p apache

rsync -a /private/etc/hosts ./apache/hosts
rsync -a /private/etc/apache2/httpd.conf ./apache/httpd2.conf
rsync -a /usr/local/etc/apache2/2.4/httpd.conf ./apache/httpd24.conf
rsync -a /usr/local/etc/httpd/httpd.conf ./apache/httpd.conf

###############################################################################

# BREW, GEM
echo -n "BACKUPS :: ... Brew, Gem Lists" | logger

rm -f ./brew.txt
# rm -f ./gem.txt

which brew | awk '{print $0}' | while read f; do "$f" list > ./brew.txt; done
# which gem | awk '{print $0}' | while read f; do "$f" list > ./gem.txt; done

###############################################################################

# SSH
echo -n "BACKUPS :: ~/.ssh" | logger

rsync -a ~/.ssh/* ./ssh

###############################################################################

# SYNC TO DROPBOX
echo -n "BACKUPS :: ... Syncing to Dropbox" | logger

mkdir -p ~/Dropbox/Pieter/backups/`ioreg -l | awk '/IOPlatformSerialNumber/ {print $4}' | sed 's|\"||g'`
rsync -au ./ ~/Dropbox/Pieter/backups/`ioreg -l | awk '/IOPlatformSerialNumber/ {print $4}' | sed 's|\"||g'`

# SAVE
echo -n "BACKUPS :: ... Commit / Push Info & Config Files" | logger

git add .
git commit -a -m "backup completed"
git push origin master

echo -n "BACKUPS :: ENDING" | logger
